[package]
name = "rust99"
version = "0.1.0"
authors = ["Jim Tracy <jamtrac@wharton.upenn.edu>"]

#[workspace]
#members = ["lists","mariatest"]

[dependencies]
mysql = "*"
#mariatest = { path = "./mariatest" }

#[dependencies.mysql]
#version = "*"
#features = ["ssl"]
