FROM mariadb
  
EXPOSE 3306

#RUN mkdir -p /usr/src/app

#COPY ./app /usr/src/app

#WORKDIR /usr/src/app

#COPY requirements.txt /usr/src/app/
#RUN pip install --no-cache-dir -r requirements.txt

VOLUME ["/var/lib/mysql"]

#CMD ["sh","entrypoint.sh"]
